//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int ShopId { get; set; }
        public int ProductId { get; set; }
        public int Tot_price { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Product Product { get; set; }
    }
}
