//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public int Id { get; set; }
        public int ShopId { get; set; }
        public double Total { get; set; }
    
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        public virtual ShopUser ShopUser { get; set; }
    }
}
