//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopUser
    {
        public ShopUser()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string ShopName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
